### ISSUE TITLE
v1.0.0 | Development Todo

### ISSUE THREAD

**Issue by ggwicz** [ggwicz/editorial#1]
**General**

- [ ] Make the various features "selectable." All should be turned on by default.

**Edit Requests**

- [X] ~~Fix the AJAX UI for the edit request publishing actions.~~
- [ ] Move metabox function in main class to edit requests class.
- [ ] Store Edit Requests in an option and use this in the dashboard widget.
- [ ] Ensure the edit request publishing actions apply changes to the stored option accurately.

**Post Lock**

- [ ] Add "Post Lock" feature

**Google Doc Link**

- [ ] Add "Google Doc Link."
- [ ] Possibly rename? "External Draft URL" link? too verbose...but maybe Google Doc is too specific?

**Internal Comments?**

- [ ] Save this for later version?

**Editorial Calendar**

- [ ] Save this for later version?
