### ISSUE TITLE
v1.0.0 | Project Todo

### ISSUE THREAD

**Issue by ggwicz** [ggwicz/editorial#2]
- [ ] Finish [Development Todo](https://github.com/ggwicz/editorial/issues/1)
- [ ] Generate WordPress.org plugin readme.txt
- [ ] Tag release 1.0.0
- [ ] Apply for plugin name on wordpress.org directory.
- [ ] Launch plugin onto WordPress.org
